<section class="headerHero wow fadeIn">
<div style="margin-left : 30px; margin-right : 30px;">
    <p style="margin-top : 5px; text-align: center;"><strong><span style="font-size: 30.5pt; font-family: '-apple-system-font',serif;">Terms of Use</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Date of Last Revision: July 27 &nbsp;2019.</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">***IMPORTANT, PLEASE READ THESE ONLINE TERMS OF USE CAREFULLY.&nbsp;</span></strong></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">YOUR USE OF AND ACCESS TO QUALITY CIRCLE INTERNATIONAL LIMITED LLC WEBSITE &ldquo;isogapauditsoftware.com&rdquo; AND IT&rsquo;S PRODUCTS AND SERVICES IS CONDITIONED UPON YOUR COMPLIANCE AND ACCEPTANCE OF THESE TERMS.</span></strong></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">***</span></strong></p>
    <ol>
        <li><strong><span style="font-size: 18.0pt; font-family: '-apple-system-font',serif;">1. Introduction</span></strong></li>
    </ol>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Welcome to the User Agreement for Quality Circle International Limited LLC.com. The Quality Circle International Limited LLC service, website and applications (collectively, &ldquo;Quality Circle International Limited LLC&rdquo; or &ldquo;the Service&rdquo;) are operated by Quality Circle International Limited LLC. This Agreement describes the terms on which you may access and use our services. By accessing or using our web site at www.isogapauditsoftware.com (&ldquo;Site&rdquo;), you (the &ldquo;User&rdquo;) signify that you have read, understood and agree to be bound by these Terms of Use (&ldquo;Terms of Use&rdquo; or &ldquo;Agreement&rdquo;), whether or not you are a registered member of Quality Circle International Limited LLC (&ldquo;Member&rdquo;).</span></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">PLEASE READ THIS AGREEMENT CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE VARIOUS LIMITATIONS AND EXCLUSIONS, AND A DISPUTE RESOLUTION CLAUSE THAT GOVERNS HOW DISPUTES WILL BE RESOLVED.</span></p>
    <ol start="2">
        <li><strong><span style="font-size: 18.0pt; font-family: '-apple-system-font',serif;">2. Eligibility</span></strong></li>
    </ol>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Membership in the Service is void where prohibited. The Quality Circle International Limited LLC Service is not available to minors under the age of 18 or to any users suspended or removed from the system by Quality Circle International Limited LLC for any reason. </span></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">&nbsp;</span></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">&nbsp;</span></p>
    <ol start="3">
        <li><strong><span style="font-size: 18.0pt; font-family: '-apple-system-font',serif;">3. Your Right and Obligations</span></strong></li>
    </ol>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Registration Details and Account Security</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">In consideration of your use of the Site, you agree to (a) provide accurate, current and complete information about you as may be prompted by any registration forms on the Site (&ldquo;Registration Details&rdquo;); (b) maintain and promptly update the Registration Details, and any other information you provide to Company, to keep it accurate, current and complete; and (c) you are responsible for maintaining the confidentiality of your password and account, and are fully responsible for all activities that occur under your password or account with or without your knowledge.</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Agreement and Warranty</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Although as an online service provider, we are not responsible for the conduct of our users, we want Quality Circle International Limited LLC to be a safe place on the internet. Therefore, in using Quality Circle International Limited LLC you represent, warrant and agree that no materials of any kind submitted through your account or otherwise posted, transmitted, or shared by you on or through the Service will violate or infringe upon the rights of any third party, including copyright, trademark, privacy, publicity or other personal or proprietary rights; or contain libelous, defamatory or otherwise unlawful material. In addition, you agree not to use the Service or the Site to:</span></p>
    <ul>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Post content or initiate communications which are unlawful, libelous, abusive, obscene, discriminatory, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable.</span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, &ldquo;junk mail,&rdquo; &ldquo;spam,&rdquo; &ldquo;chain letters,&rdquo; &ldquo;pyramid schemes,&rdquo; or any other form of solicitation. This prohibition includes, but is not limited to a) Using Quality Circle International Limited LLC to connect to people who don&rsquo;t know you and then sending unsolicited promotional messages to those direct connections without their permission; and b) Sending messages to distribution lists, newsgroup aliases, or group aliases.</span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Use the Service or the Site in any unlawful manner or in any other manner that could damage, disable, overburden or impair the Site; use automated scripts to collect information from or otherwise interact with the Service or the Site;</span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Falsely state, impersonate, or otherwise misrepresent your identity, including but not limited to the use of a pseudonym, uploading photographs of celebrities in your profile, or misrepresenting your current or previous positions and qualifications, or your affiliations with a person or entity, past or present; upload, post, transmit, share, store or otherwise make publicly available on the Site any private information of any third party, including, without limitation, addresses, phone numbers, email addresses, Social Security numbers and credit card numbers.</span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Upload, post, transmit, share or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; intimidate or harass another.</span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Sell, rent, or otherwise provide your contacts/other users contact information to any third party for marketing purposes. Further you cannot use your contact/other users&rsquo; contact information for marketing purposes.</span></li>
    </ul>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Global Use</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Recognizing the global nature of the Internet, you agree to comply with all applicable local rules including but not limited to rules regarding online conduct and acceptable content. Specifically, you agree to comply with all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside.</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Copyright Policy</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">You may not post, modify, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information belonging to others without obtaining the prior written consent of the owner of such proprietary rights. It is Quality Circle International Limited LLC&rsquo;s policy to terminate Membership privileges of any Member who repeatedly infringes the copyright rights of others upon receipt of prompt notification to Quality Circle International Limited LLC by the copyright owner or the copyright owner&rsquo;s legal agent. Without limiting the foregoing, if you believe that your work has been copied and posted on the Quality Circle International Limited LLC Services in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: </span></p>
    <ul>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; </span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">(ii) a description of the copyrighted work that you claim has been infringed;</span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">(iii) a description of where the material that you claim is infringing is located on the Quality Circle International Limited LLC Services; </span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">(iv) your address, telephone number, and email address; </span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">(v) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; </span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">(vi) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner&rsquo;s behalf. Quality Circle International Limited LLC&rsquo;s Copyright Agent for notice of claims of copyright infringement can be reached as follows: Copyright Agent, Quality Circle International Limited LLC.</span></li>
        <li><span style="font-family: 'Helvetica',sans-serif;">It is the responsibility of the company backup all information on their own server at their chosen frequency. We utilize the highest level of controls for our domain are very confident of its security capabilities. However, we do not take responsibility for loss of information. </span></li>
    </ul>
    <p style="margin-left: 1.0in; text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">&nbsp;</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Fees &amp; Payment</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">You agree that Quality Circle International Limited LLC may charge to Your credit card or other payment mechanism selected by You and approved by Quality Circle International Limited LLC (&ldquo;Your Account&rdquo;) all amounts due and owing for the Services, including Service fees, set up fees, subscription fees, or any other fee or charge associated with Your Account. Quality Circle International Limited LLC may change prices at any time, including changing from a free service to a paid service and charging for Services that were previously offered free of charge; provided, however, that Quality Circle International Limited LLC will provide you with prior notice and an opportunity to terminate Your Account if Quality Circle International Limited LLC changes the price of a Service to which you are subscribed and will not charge you for a previously free Service unless you have been notified of the applicable fees and agreed to pay such fees. You agree that in the event Quality Circle International Limited LLC is unable to collect the fees owed to Quality Circle International Limited LLC for the Services through Your Account, Quality Circle International Limited LLC may take any other steps it deems necessary to collect such fees from You and that You will be responsible for all costs and expenses incurred by Quality Circle International Limited LLC in connection with such collection activity, including collection fees, court costs and attorneys&rsquo; fees. You further agree that Quality Circle International Limited LLC may collect interest at the lesser of 1.5% per month or the highest amount permitted by law on any amounts not paid when due. You may cancel your subscription at any time. If you cancel, you will not be billed for any additional terms of service, and service will continue until the end of the current Subscription Term. If you cancel, you will not receive a refund for any service already paid for.</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Quality Circle International Limited LLC Communications</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">You agree to receive communications from Quality Circle International Limited LLC in connection with your use of Quality Circle International Limited LLC Services in the form of email or SMS messages, including without limitation account activity notification, service updates, and reminders.</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Privacy Policy</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Privacy Use of the Quality Circle International Limited LLC Services is also governed by our Privacy Policy, which is incorporated into this Agreement by this reference. By accepting this User Agreement, you agree to indemnify and otherwise hold harmless Quality Circle International Limited LLC Corporation, its officers, employees, agents, subsidiaries, affiliates and other partners from any direct, indirect, incidental, special, consequential or exemplary damages resulting from </span></p>
    <ol>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">your use of the Quality Circle International Limited LLC Service; </span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">unauthorized access to or alteration of your communications with or through the Quality Circle International Limited LLC Service, or </span></li>
    </ol>
    <ul>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">any other matter relating to the Quality Circle International Limited LLC Service. Any business transactions which may arise between users from their use of Quality Circle International Limited LLC are the sole responsibility of the users involved.</span></li>
    </ul>
    <ol start="4">
        <li><strong><span style="font-size: 18.0pt; font-family: '-apple-system-font',serif;">4. Our Rights and Obligations</span></strong></li>
    </ol>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Proprietary Rights in Site Content; Limited License</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">All content on the Site and available through the Service, including but not limited to designs, text, graphics, pictures, video, information, applications, software, music, sound and other files, and their selection and arrangement (the &ldquo;Site Content&rdquo;), are the proprietary property of the Company, its users or its licensors with all rights reserved. No Site Content may be modified, copied, distributed, framed, reproduced, republished, downloaded, displayed, posted, transmitted, or sold in any form or by any means, in whole or in part, without the Company&rsquo;s prior written permission.</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;">&nbsp;</span></strong></p>
    <ol start="5">
        <li><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;"> Termination</span></strong></li>
    </ol>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Rights of Termination</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">The Company may terminate your membership, delete your profile and any content or information that you have posted on the Site or through any Platform Application and/or prohibit you from using or accessing the Service or the Site or any Platform Application (or any portion, aspect or feature of the Service or the Site or any Platform Application) for any reason, or no reason, at any time in its sole discretion, with or without notice. Furthermore, you agree that all terminations shall be made in Quality Circle International Limited LLC&rsquo;s sole discretion and that Quality Circle International Limited LLC shall not be liable to you nor any third-party for any termination of your account or access to the Quality Circle International Limited LLC Service.</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Repeat Infringer Policy</span></strong></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">In accordance with the Digital Millennium Copyright Act (DMCA) and other applicable law, Company has adopted a policy of terminating, in appropriate circumstances and at Company&rsquo;s sole discretion, Members who are deemed to be repeat infringers. Company may also at its sole discretion limit access to the Site and/or terminate the memberships of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.</span></p>
    <ol start="6">
        <li><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;"> Disclaimer of Warranties</span></strong></li>
    </ol>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">YOU UNDERSTAND AND AGREE THAT THE Quality Circle International Limited LLC SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS AND THAT Quality Circle International Limited LLC DOES NOT ASSUME ANY RESPONSIBILITY FOR PROMPT OR PROPER DELIVERY, OR RETENTION OF ANY USER INFORMATION OR COMMUNICATIONS BETWEEN USERS. Quality Circle International Limited LLC ASSUMES NO RESPONSIBILITY FOR THE ACCURACY OR EXISTENCE OF ANY COMMUNICATIONS BETWEEN USERS. Quality Circle International Limited LLC EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.<br />Quality Circle International Limited LLC MAKES NO WARRANTY THAT</span></p>
    <ul>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">THE Quality Circle International Limited LLC SERVICE WILL MEET YOUR REQUIREMENTS, </span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">THE Quality Circle International Limited LLC SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, </span></li>
        <li><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED.<br />ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE Quality Circle International Limited LLC SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Quality Circle International Limited LLC OR THROUGH OR FROM THE Quality Circle International Limited LLC SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS USER AGREEMENT.<br />SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</span></li>
    </ul>
    <ol start="6">
        <li><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;"> Limitation of Liability</span></strong></li>
    </ol>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">YOU EXPRESSLY UNDERSTAND AND AGREE THAT Quality Circle International Limited LLC AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, OPPORTUNITY, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF Quality Circle International Limited LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM USE OF THE WEBSITE OR ANY RELATED/UNRELATED SERVICES AND OTHER SERVICES OFFERED ON THE WEBSITE FROM TIME TO TIME. IN NO EVENT WILL Quality Circle International Limited LLC&rsquo;S TOTAL CUMULATIVE DAMAGES EXCEED US$ 50.</span></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">&nbsp;</span></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">&nbsp;</span></p>
    <ol start="7">
        <li><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;"> Governing Law</span></strong></li>
    </ol>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">&ldquo;The User Agreement between you and Quality Circle International Limited LLC Inc., will be governed by, and construed in accordance with the laws in force in (a) the State of Delaware. </span></p>
    <ol start="8">
        <li><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;"> Submissions</span></strong></li>
    </ol>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the Site or the Service (&ldquo;Submissions&rdquo;), provided by you to Company are non-confidential, and shall become the sole property of Company. Company shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.</span></p>
    <p style="text-align: justify;"><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;">&nbsp;</span></strong></p>
    <ol start="9">
        <li><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;"> Other</span></strong></li>
    </ol>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">This Agreement is accepted upon your use of the Quality Circle International Limited LLC Website or any of the Quality Circle International Limited LLC Services and is further affirmed by you becoming a Member. This Agreement constitutes the entire agreement between you and Quality Circle International Limited LLC regarding the use of the Quality Circle International Limited LLC Services. The failure of Quality Circle International Limited LLC to exercise or enforce any right or provision of this Agreement will not operate as a waiver of such right, or provision. The section titles in this Agreement are for convenience only, and have no legal or contractual effect. This Agreement operates to the fullest extent permissible by law. If any provision of this Agreement is unlawful, void or unenforceable, that provision is deemed severable from this Agreement and does not affect the validity and enforceability of any remaining provisions.</span></p>
    <ol start="10">
        <li><strong><span style="font-size: 15.0pt; font-family: '-apple-system-font',serif;"> Contact Information</span></strong></li>
    </ol>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Quality Circle International Limited LLC welcomes your questions or comments regarding these Terms by emailing us at legal@qualitycircleint.com</span></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Email:&nbsp;<span style="color: windowtext;"><a href="mailto:support@qualitycircleint.com">support@qualitycircleint.com</a></span></span></p>
    <p style="text-align: justify;"><span style="font-size: 13.5pt; font-family: '-apple-system-font',serif;">Website:&nbsp;</span><span style="font-size: 16.0pt;">www.qualitycircleint.com</span></p>
    <p style="text-align: justify;">&nbsp;</p>
</div>
<?php $this->load->view('admin/footer');?>